apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backplane-ingress-controller
  labels:
    k8s-app: backplane-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: backplane-ingress-controller
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: bpagent
        image: backplaneio/backplane
        args:
         - "connect"
         - "$(BACKPLANE_LABELS)"
         - "http://127.0.0.1:80"
        env:
         - name: BACKPLANE_TOKEN
           valueFrom:
             secretKeyRef:
               name: backplane-token
               key: bptoken
         - name: BACKPLANE_LABELS
           valueFrom:
             configMapKeyRef:
               name: backplane-config
               key: labels
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.5
        name: nginx-ingress-controller
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
